name: pay_sync
description: "PaySync - Payment tracking and SMS monitoring app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Dependency Injection
  injectable: ^2.5.1
  get_it: ^8.2.0

  # Navigation
  go_router: ^14.6.1

  # UI & Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2

  # SMS & Telephony
  another_telephony: ^0.4.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
flutter:
  uses-material-design: true
