name: pay_sync
description: "PaySync - Payment tracking and SMS monitoring app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # SMS & Permissions
  permission_handler: ^11.3.1
  another_telephony: ^0.4.1

  # Background Processing & Services
  workmanager: ^0.5.2
  flutter_foreground_task: ^8.5.0
  device_info_plus: ^10.1.0

  # Local Database & Storage
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Utilities
  intl: ^0.19.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  connectivity_plus: ^6.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
